name: telegram-poster

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: send message to telegram channel
        run: python tg_bot.py
        env:
          BERKANTKZBOT: ${{ secrets.BERKANTKZBOT }} 
