name: telegram-poster

on:
  workflow_run:
    workflows: ["pages build and deployment"]
    types:
      - completed

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
    - name: publish post on telegram
      run: python tg_bot.py
